var constants = {
    SEVERITY_DEBUG: -1,
    SEVERITY_NORMAL: 0,
    SCREEN_PRINT_INFO: 0,
    SCREEN_PRINT_SAVE: 1,
    SCREEN_PRINT_ERROR: 2,
    SCREEN_PRINT_HEADING: 3,
    SCREEN_PRINT_FILE: 4,

    STEP_START: 1,
    STEP_JUST_LOADED_CONFIG: 2,
    STEP_JUST_READ_ALL_FROM_SERVER: 3,
    STEP_JUST_SAVED_ALL_FILES_TO_DISK: 4,
    STEP_JUST_UPLOADED_DDMS: 5,
	STEP_JUST_CREATED_PROJECT: 6
};

module.exports = constants;